# SearXNG Limiter Configuration
# See https://docs.searxng.org/admin/settings.html#limiter for details

[botdetection.ip_limit]

# filters = ['ip']
# suspicious_ip_window = 3600
# suspicious_ip_max = 10

[botdetection.ip_lists]

# pass_ip = [
#   '192.168.0.0/16',
#   '10.0.0.0/8',
#   '172.16.0.0/12'
# ]
# block_ip = [
#   '93.184.216.34'
# ]
